### ISSUE TITLE
react/addons

### ISSUE THREAD

**Issue by aguilera51284** [juhaelee/material-ui-io#3]
I 'm using the library , and I get this error when I import.

Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.

im use react 0.14.0-rc1

**Comment by juhaelee** [comment]
Fell free to create a pull request, but I am no longer supporting this library (besides merging pull requests). I am currently creating my own library on top of [mdl.io](http://www.getmdl.io/)
